### ISSUE TITLE
Assists for a particular season?

### ISSUE THREAD

**Issue by LePetitNewbie** [akarabat/AssistScraper#1]
Hi Akarabat
           There is no issue. Just thought I would ask if there is a way to only get the assists data for a particular season? I do not have any coding experience. Just like to check on the data. thanks

Ol

**Comment by akarabat** [comment]
Hey, sure, I can help you with that. Do you want me to send you data for a particular season (and if so, which season), or do you want help figuring out how to, in general, create the dataset for a particular season?

**Comment by LePetitNewbie** [comment]
Hi Mate
       Thanks for the reply. Yeah so the 2nd option if you could help me figure out how to create the dataset for a particular season.  Appreciate your help

Cheers
Ol

**Comment by akarabat** [comment]
Hey, my earlier response was a little confused because I thought this was posted on my other NBA assists project (which creates a dataset of all assists in the NBA from 1996 to today). 

What I've done is edit the main function in the program, getAssists(). Now, instead of taking one argument (the url of the player in question), it can optionally take two arguments. The second argument, called "foryears", is a list of years that you want to search over. By default, this argument will have the value 'all', which is a little messy, but basically means that you can ignore it in your call. So this: getAssists("https://www.basketball-reference.com/players/j/jamesle01.html") is still a valid call of the function. Since in this call I didn't specify a value for "foryears", it defaults to all years.

But you can also call the function like getAssists("https://www.basketball-reference.com/players/j/jamesle01.html", years=['2005', '2006,' ,'2007', '2009']) if you want to, and it will return Lebron James's assists in those years only. The years are the second part of the year in a season, following the standard from basketball-reference.com, so the 2004-2005 season is '2005' here. 

To make this adjustment, what I did was add the code 

    if foryears[0] != 'all':
        newyears = []
        for y in foryears:
            ycheck = '/players/' + myID[0] + '/' + myID + '/gamelog/' + y
            if ycheck in years:
                newyears.append(ycheck)
        years = newyears.copy()

Just before this block of code, there is a list called years that is created. This list is created by looking at a players basketball reference page and seeing what years the player played games in. It creates a list of all of these years.

The if condition starts off the new process. It looks at the first element of the list foryears (in some languages, like python, the first element is in the zero position), and checks if that value is equal to 'all' (the default value). If it is, the process within the if statement is skipped (!= means "not equal to"). Otherwise, the process is carried out. The process creates a new list called newyears, which will replace years. But we don't want to put years in there that the player didn't actually play, so it checks each year in the foryears argument, and if that year is also in years, it puts the year in newyears. Then at the end, it replaces the years list with our newyears list.

**Comment by LePetitNewbie** [comment]
Hi Mate
        Sorry for the late reply. Thanks for your help. I will check your other NBA assists project. I am really new to all of this and got lost even though you did try to explain it and I really appreciate you taking the time to try and help. I am not really sure where to add the code or what to modify.  ( I Did add the years but unsure if the code needs to be put somewhere specific. I'll check the other project. Hopefully I'll find a way.

Cheers

**Comment by LePetitNewbie** [comment]
Hi Akarabat

    I thought i would let you know that after reading it a few times, I managed to get it to work. I only realised that you added the block of code to the page ... I was still using the script i copied from github. Anyways , I really appreciate the effort & really enjoy using it ! thanks again and enjoy christmas.

Ol
